export default {
    title:"Mustard",
    links:[
        {
            name:"Home",
            link:"/"
        },
        {
            name:"Friends",
            link:"/friends"
        },{
            name:"Notifications",
            link:"/notifications"
        },{
            name:"You",
            link:"/profile"
        }
    ],
    authButtons:[{
        name:"Login",
        link:"/login"
    },{
        name:"Sign Up",
        link:"/signup"
    }],
    unauthButtons:[{
        name:"Profile",
        link:"/profile"
    },{
        name:"Settings",
        link:"/settings"
    }]
}